catalog/urls.py
from django.urls import include, path, re_path
from . import views
urlpatterns = [
    path('',views.index, name='index'),
    path('books/',views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/',views.LoanedBooksbyUserListView.as_view(), name='my-borrowed')
]
# urlpatterns += [
#     path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
# ]

locallibrary/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    """Models reprenting a book genre"""
    name = models.CharField(max_length=200, help_text= "Enter a book genre(e.g. Science Fiction")

    def __str__(self):
        """String for representing the Model object"""
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200, help_text= "Enter the book's natural language(e.g. English, French, Japanese etc.)")
    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete= models.SET_NULL, null = True)
    summary = models.TextField(max_length=1000, help_text = "Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete = models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'Genre'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default= uuid.uuid4, help_text= 'Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrowed = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS =(
        ('m','Maintenance'),
        ('o', 'On loan'),
        ('a','Available'),
        ('r','Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices= LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
    def __str__(self):
        return f"{self.id}({self.book.title})"

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null = True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'
 

    

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = "Enter a date between now and 4 weeks (default 3)")

    def clean_renewal_date(self):
        data = self.clean_data['renewal_date']
        
        #check if a date is in the past
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))

        return data

        

catalog/views.py
from django.shortcuts import render
from .models import*
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm

def index(request):
    num_books = Book.objects.all().count()
    num_copies = BookInstance.objects.all().count()
    #Available book (status = 'a')
    num_available_book = BookInstance.objects.filter(status__exact = 'a').count()
    num_authors = Author.objects.count()
    books = Book.objects.filter(title__icontains = 'code')
    book_list = []
    for book in books:
        book_list.append(book)
    num_visits = request.session.get('num_visits',1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books' : num_books,
        'num_books_instance' : num_copies,
        'num_available_book': num_available_book,
        'num_authors' : num_authors,
        'book_list': book_list,
        'num_visits' : num_visits,
    }
    return render(request, 'index.html', context = context)
class BookListView(generic.ListView):
    model = Book
    context_object_name = "my_book_list" #defaul la book_list
    template_name = 'catalog/my_book_list.html' #neu co file my_book_list.html thi no chay file day
    #default theo django thi chay file book_list.html
    paginate_by = 2
    def get_queryset(self):
        return Book.objects.all()[:3]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["test_content"] = "test_get_content"
        return context 

class BookDetailView(generic.DetailView):
    model = Book
    #default context_object_name is book
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 2
class AuthorDetailView(generic.DetailView):
    model = Author
class LoanedBooksbyUserListView(LoginRequiredMixin ,generic.ListView):
    model = BookInstance
    context_object_name = 'loaned_books'
    template_name = 'catalog/bookinstance_list_borrowed_by_user.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrowed = self.request.user).filter(status__exact = 'o').order_by('due_back')

# def renew_book_librarian(request, pk):
#     book_instance = get_object_or_404(BookInstance, pk=pk)

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %} <title>Local Library</title> {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block scripts %}
    {% endblock scripts %}
</head>
<body>
   <div class="container-fluid">
      <div class='row'>
          <div class = 'col-sm-2'>
           {% block sidebar %}
            <ul class='sidebar-nav'>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'books' %}">All books</a></li>
                <li><a href="{% url 'authors' %}">All authors</a></li>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'my-borrowed' %}">My borrowed</a></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
           {% endblock %}

          </div>
          <div class = 'col-sm-10'>
            {% block content %}
            {% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                    <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                    </span>
                    </div>
                {% endif %}
            {% endblock %}
          </div>
      </div> 
   </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Author : {{author.last_name}} {{author.first_name}}</h1>
  <p>{{author.date_of_birth}} - {% if author.date_of_death %}
    {{author.date_of_death}}
    {% else %}
    <span>Still alive</span>
  {% endif %}</p>
  <div style="margin-top: 20px; margin-left: 20px;">
    <h5>Books</h5>
    <ul>
        {% for book in author.book_set.all %}
            <li>
                <p><strong><a href="{{book.get_absolute_url}}">{{book.title}}</a></strong></p>
                <p>Summary: {{book.summary}}</p>
            </li>
            
        {% endfor %}
    </ul>
    

  </div>
  
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
    <ul>
        {% for author in author_list %}
            <li><a href="{{author.get_absolute_url}}">{{author.last_name}} {{author.first_name}}</a>({{author.date_of_birth}}-{{author.date_of_death}})</li>
        {% endfor %}
    </ul>
    
  {% else %}
    <p>There is no author</p>
  {% endif %}
{% endblock content %}<h1>Author List</h1>

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{book.title}}</h1>
<p><strong>Author: </strong>{{book.author}}</p>
<p><strong>Summary: </strong>{{book.summary}}</p>
<p><strong>ISBN: </strong>{{book.isbn}}</p>
<p><strong>Languge: </strong>{{book.language}}</p>
<p><strong>Genre: </strong>{{book.genre}}</p>
<div style="margin-top : 20px; margin-left: 20px;">
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger {% else %}text-warning {% endif %}">
          {{copy.get_status_display}}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to back: </strong>{{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint: </strong>{{copy.imprint}}</p>
      <p class = "text-mute"><strong>Id: </strong>{{copy.id}}</p>
    {% endfor %}

</div>

  
{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% block title %}
  <title>Books List</title>
{% endblock title %}
{% block content %}
   <h1>Book List </h1> 
   {% if my_book_list %}
     <ul>
         {% for book in my_book_list  %}
            <li>
                <a href="{{book.get_absolute_url}}">{{book.title}}</a>({{book.author}})-({{test_content}})
            </li>
           
         {% endfor %}
     </ul>
   {% else %}
     <p>There no books in library</p>
   {% endif %}
   
{% endblock content %}  

catalog/templates/catalog/bookinstance_list_borrowed_by_user.html
{% extends "base_generic.html" %}

{% block content %}
   <h1>Borrowed Books</h1>
   {% if loaned_books %}
    <ul>
        {% for book in loaned_books %}
            <li class="{% if book.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'book-detail' book.book.pk %}">{{book.book.title}}</a>({{ book.due_back }})
            </li>
        {% endfor %}
    </ul>
   {% else %}
    You haven't borrowed yet.
   {% endif %}
   
   
{% endblock content %}

catalog/templates/index.html
{% extends "base_generic.html" %}
{% block title %}
  <title>Home</title>
{% endblock title %}
{% block content%}<title>Van Dien</title>
    <h1>Local Library</h1>
    <p>Welcome my library</p>
    <h2>Dynamic content</h2>
    <ul>
        <li><strong>Books: </strong>{{ num_books }}</li>
        <li><strong>Copies: </strong>{{ num_books_instance }}</li>
        <li><strong>Copies available: </strong>{{ num_available_book }}</li>
        <li><strong>Authors : </strong>{{ num_authors }}</li>
        <li><strong>Book_list_code: </strong>{% for book in book_list  %}
            <ul>{{book.title}}</ul>
        {% endfor %}</li>
    </ul>
    <p>You have visited this page {{num_visits}} time</p>
  
{% endblock  %}